package com.example.compose_materialtest.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4B6700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC2F358)
val md_theme_light_onPrimaryContainer = Color(0xFF141F00)
val md_theme_light_secondary = Color(0xFF6351A5)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE7DEFF)
val md_theme_light_onSecondaryContainer = Color(0xFF1F005F)
val md_theme_light_tertiary = Color(0xFF006D36)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF6CFE9C)
val md_theme_light_onTertiaryContainer = Color(0xFF00210C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF001B3D)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
val md_theme_light_inverseSurface = Color(0xFF003062)
val md_theme_light_inversePrimary = Color(0xFFA7D63E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4B6700)
val md_theme_light_outlineVariant = Color(0xFFC6C8B9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA7D63E)
val md_theme_dark_onPrimary = Color(0xFF253600)
val md_theme_dark_primaryContainer = Color(0xFF374E00)
val md_theme_dark_onPrimaryContainer = Color(0xFFC2F358)
val md_theme_dark_secondary = Color(0xFFCCBDFF)
val md_theme_dark_onSecondary = Color(0xFF341F74)
val md_theme_dark_secondaryContainer = Color(0xFF4B388C)
val md_theme_dark_onSecondaryContainer = Color(0xFFE7DEFF)
val md_theme_dark_tertiary = Color(0xFF4BE083)
val md_theme_dark_onTertiary = Color(0xFF003919)
val md_theme_dark_tertiaryContainer = Color(0xFF005227)
val md_theme_dark_onTertiaryContainer = Color(0xFF6CFE9C)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001B3D)
val md_theme_dark_onBackground = Color(0xFFD6E3FF)
val md_theme_dark_surface = Color(0xFF001B3D)
val md_theme_dark_onSurface = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant = Color(0xFF45483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B9)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary = Color(0xFF4B6700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA7D63E)
val md_theme_dark_outlineVariant = Color(0xFF45483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF7AA600)
